"""empty message

Revision ID: 6b9e239c4bc1
Revises: 
Create Date: 2021-05-25 11:38:10.418013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9e239c4bc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('hospital',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_table('doctor_hospital',
    sa.Column('doctor_hospital_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ),
    sa.PrimaryKeyConstraint('doctor_hospital_id')
    )
    # ### end Alembic commands ###
    op.execute("""
        INSERT INTO hospital 
        (name, description, phone, start_year)
        VALUES
        ('Hoag','A good hospital','606-330-0123',1999),
        ('Another Hospital', 'New hospital', '612-321-1234',2005);
        
        INSERT INTO doctors
        (first_name,last_name,categories,languages,experience)
        VALUES
        ('Hang','Guo','{internal medicine,pediatrics}','{English,Mandarin,Cantonese}',7),
        ('Vickey','Liu','{internal medicine,Obstetrics}','{English,Mandarin}',9);
        
        
        
        
        INSERT INTO doctor_hospital 
        (hospital_id, doctor_id,start_date) 
        SELECT h.hospital_id, d.doctor_id, '2012-01-05'
        FROM hospital h
        CROSS JOIN doctors d
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_hospital')
    op.drop_table('hospital')
    op.drop_table('doctors')
    # ### end Alembic commands ###
